defaults:
  - training
  - model_size: tiny
  - _self_

dataset:
  splits:
    - train
    - validation

scaling:
  enabled: true
  avg_audio_seconds: 15.0

optimization:
  max_steps: 100000000

evaluation:
  validation_every_steps: 100
  max_eval_batches: 16
  compute_train_metrics: false

wer:
  enabled: false

wandb:
  tags:
    - scaling-laws

runtime:
  save_every_steps: 100000000
  test_only: false
  output_dir: ${hydra:runtime.output_dir}

hydra:
  sweep:
    dir: out/scaling
    subdir: ${scaling.model_name}/D_${scaling.target_tokens}/lr_${path_token:${optimization.lr}}/seed_${runtime.seed}
